### ISSUE TITLE
Modules won't show up in VCV on Windows 10 Pro

### ISSUE THREAD

**Issue by caecos** [alexey-komarov/fruitsofkarma-vcvrack#1]
I've compiled your modules but they will not show up in the menu of VCV even if compilation is ok and the folder is in the plugin folder of VCV:

$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nehalem -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -municode  -c -o build/src/ColoredGlass.cpp.o src/ColoredGlass.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nehalem -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -municode  -c -o build/src/Quadro360.cpp.o src/Quadro360.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nehalem -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -municode  -c -o build/src/plugin.cpp.o src/plugin.cpp
g++ -o plugin.dll build/src/ColoredGlass.cpp.o build/src/Quadro360.cpp.o build/src/plugin.cpp.o -shared -LC:/msys64/Rack-SDK -lRack -static-libstdc++
rm -rf dist
mkdir -p dist/fruitsofkarma
cp plugin.dll dist/fruitsofkarma/
strip -s dist/fruitsofkarma/plugin.dll
cp -r --parents res LICENSE plugin.json dist/fruitsofkarma/
cd dist && tar -c fruitsofkarma | zstd -19 -o "fruitsofkarma"-"1.0.0"-win.vcvplugin

**Comment by alexey-komarov** [comment]
Thank you for you report, I haven't yet tested the build on anything except my linux, hopefully will do this next week or so.

**Comment by caecos** [comment]
Merci!

**Comment by alexey-komarov** [comment]
@caecos I had built it on windows 10 for Rack2 (with bumped plugin version to 2.0.0) , the same issue.
I also checked the log.txt in Rack dir, it says:
[0.042 warn src/plugin.cpp:174 loadPlugin] Could not load plugin C:/Users/Virtual/Documents/Rack2/plugins/fruitsofkarma-vcvrack: Failed to load library C:/Users/Virtual/Documents/Rack2/plugins/fruitsofkarma-vcvrack/plugin.dll: code 193 which apparently means that a 64 bit operating system is trying to load a 32 bit Win32 file. 
Looks really strange to me, could you please check if you have the same error in your log.txt?

**Comment by caecos** [comment]
.975 info src/plugin.cpp:121 loadPlugin] Loading plugin from C:/Users/caeco/OneDrive/Documents/Rack2/plugins/fruitsofkarma
[2.167 warn src/plugin.cpp:174 loadPlugin] Could not load plugin C:/Users/caeco/OneDrive/Documents/Rack2/plugins/fruitsofkarma: Plugin version 1.0.0 does not match Rack ABI version 2
[2.167 info src/plugin.cpp:121 loadPlugin] Loading plugin from C:/Users/caeco/OneDrive/Documents/Rack2/plugins/Fundamental

**Comment by caecos** [comment]
It seems that you does not used the right SDK!!!

**Comment by alexey-komarov** [comment]
@caecos 
There is a version of plugin in json file https://github.com/alexey-komarov/fruitsofkarma-vcvrack/blob/main/plugin.json#L4
First number apparently means number of the Rack version. I will create a separate branch for the v2 a bit later when fix couple of remaining things. If you want to build my plugin for Rack2, just set version to be 2.0.0 in the plugin.json.

Also, I was able to build and run it on windows in Rack1 and Rack2. That was a very weird thing. Everything was good when I excluded ColoredGlass from build, all other 3 modules were shown in vcvrack np. Then I started to remove code from coloredglass until there was just empty skeleton, and it didn't solve the issue, it still didn't want to show up. Only one thing remained to try, to rename svg file to be not longer than 8 char. It was crazy idea especially in 2022, because as I see other plugins don't have this issue. But once I renamed ColoredGlass.svg to ColoredGl.svg and rebuild my plugin, it magically started to work on Rack1 and Rack2. 

Then I tried to reproduce the bug and surprisingly I wasn't able to do that. I checked out my changed, renamed the svg back, build plugin again and it works again without any issue. Don't know what to think, Windows is a strange thing, that's why i'm not using it. :)

Can you try to build my plugin with version 2.0.0 in JSON. If still doesn't show up, you can do git pull to get latest changes, I just renamed ColoredGlass.svg in the repo, just in case if someone else catches the same issue as me.

**Comment by caecos** [comment]
Hi Alexey,

I’ve compiled the sources and renamed the json file 2.0.0 instead of 1.0.0 and it all works. Strange behavior Indeed, but it’s Windows…

Regards,

Marc


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Alexey ***@***.***>
Envoyé le :mercredi 4 mai 2022 16:14
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [alexey-komarov/fruitsofkarma-vcvrack] Modules won't show up in VCV on Windows 10 Pro (Issue #1)


@caecos<https://github.com/caecos>
There is a version of plugin in json file https://github.com/alexey-komarov/fruitsofkarma-vcvrack/blob/main/plugin.json#L4
First number apparently means number of the Rack version. I will create a separate branch for the v2 a bit later when fix couple of remaining things. If you want to build my plugin for Rack2, just set version to be 2.0.0 in the plugin.json.

Also, I was able to build and run it on windows in Rack1 and Rack2. That was a very weird thing. Everything was good when I excluded ColoredGlass from build, all other 3 modules were shown in vcvrack np. Then I started to remove code from coloredglass until there was just empty skeleton, and it didn't solve the issue, it still didn't want to show up. Only one thing remained to try, to rename svg file to be not longer than 8 char. It was crazy idea especially in 2022, because as I see other plugins don't have this issue. But once I renamed ColoredGlass.svg to ColoredGl.svg and rebuild my plugin, it magically started to work on Rack1 and Rack2.

Then I tried to reproduce the bug and surprisingly I wasn't able to do that. I checked out my changed, renamed the svg back, build plugin again and it works again without any issue. Don't know what to think, Windows is a strange thing, that's why i'm not using it. :)

Can you try to build my plugin with version 2.0.0 in JSON. If still doesn't show up, you can do git pull to get latest changes, I just renamed ColoredGlass.svg in the repo, just in case if someone else catches the same issue as me.
